### ISSUE TITLE
support auto-compress of attachments

### ISSUE THREAD

**Issue by asarubbo** [radhermit/bugbite#34]
Atm the gentoo bugzilla supports attachment with a maximum size of 1024kb.

Would be great if when the size of the attachment is greater than 1024kb (e.g. $BUGBITE_MAX_ATTACHMENT_SIZE variable), bite compress it and attachs it as compressed.
That should be done in presence of, for example, --auto-compress-attachment option.

This scenario has two possible way:
1) the size of the compressed log is less then 1024kb, then suitable for the attachment.
2) the size of the compressed log is still greater then 1024kb, then NOT suitable for the attachment.
In such case(2), another option like --cut-compressed-log-lines $N can help where N are the lines you want to attach. This should be a way to post at least the latest $N lines of the log.

Atm, for compress logs I'm using xz, and I verified that it gives the best ratio compression. With the recent changes in xz, I'm using: `xz -k -z -9 -T 1 -M 3000000000 "${BUILD_LOG}"`
but I suppose that apart `-z` we can use something like $BUGBITE_XZ_OPTS

**Comment by radhermit** [comment]
Compression support could probably be altered via some config settings, e.g. default compression (with an internal default as well), along with wrappers for common types that would be added to the bugbite lib so other frontends could make use of it more easily.

I'd rather push user configuration towards that design (assuming a better config file gets designed as well) than supporting lots of environment variables although some of the settings could still support pulling from both where it makes sense.
