### ISSUE TITLE
"bite modify --blocks" overwrite the entire "Blocks" field

### ISSUE THREAD

**Issue by asarubbo** [radhermit/bugbite#64]
While blocking bugs with:
```
 bite -s bugzilla -c gentoo modify --blocks "${X}" "${BUG_NUMBER}"
```

I noticed that it completely overwrite the "Blocks" field instead of just adding $X to the list of the blocked bugs.

Real example here:
https://bugs.gentoo.org/show_activity.cgi?id=936926

**Comment by radhermit** [comment]
See the related documentation in the man page or at https://radhermit.github.io/bugbite/bite-bugzilla-update.html, unprefixed values override the entire field on purpose.

In order to add a value use the `+` prefix.

**Comment by radhermit** [comment]
Also, I don't think this was changed after the most recent release, but I could make new releases soon if necessary.
